def bwt(text):
    matrix = []
    for j in range(len(text)):
        line = text[j:] + text[:j]
        matrix.append(line)
    sortedMatrix = sorted(matrix)
    result = ""
    for i in sortedMatrix:
        result += str(i[-1])
    return result

print(bwt([*"ATGATGACTCACCCAGGTTCGCAAATTACACCCGTACAATGCAGATGGTCGGATGAGTCATTTACAGGTCCCAAGCATACTCAAGGTAAATCACGGGGCACGGCATGGAATTGCTGCTGGACGTGGTTAAAGTTCAGTAGAGCTTAGACGGTCCTTGGAAAGACCTTCGGAGAGGCACTAAGATACGTAGCACACTCACACGAAGGTTTTTTCTTAGCAATCGGATGCCATTCAATGCACATTGGTTCTTAAGACCAACCACTGCCCCTTGTATTGCCGCTGAAAATAACCTCTAGCGGCCTCCGTAGCGAAGATTCCTACCATTCCGCAGGGGCACCTCGCGTAAAGCGCTAATGACCCGTCATTTTAATACCTCGTGGATACCACAATCAGTGATGTCTAATCCCAAGCCACTGAGGCTGCAGGAATCACGAATGTCCTCTTGAAGCCAATTCACTTTTGCATCGTCGACGAACATCGCAAAACCTTCGCGTGCTTAAGTCTCTCACGCACGAGTCTTGAGCCACACCACTTATGCACCTGCTTCGATTCAGAAGGACTATCTACCGTGTGACACATCCAGCCAAGCCCCCGCAAGCTCAGTTCGTACATCAGCGCACTTAAAATTAACTCTGCAGGCCGGGACTGTACGTCGAAGACTATTGGTTCCTGACGGTAGCAGATTGAAGTGCACGCGAAATCCACGAAAACCACGGGTACGATACACGCATGATGACTTCACGAAACACACACAAGATTCATTACAGTGAGTTAAATGCCGAGTCGATTACATCCATTCAACCGGCAGTTAACCCGACCTCTGTCATGAGTTCCGCCATCGGGCCCATTTACGGTTATCTGCAGGGTCTCGTTGTGCGATGTATGAGCTCGGCAACGACACGGGGCTGACACAACA$"]))